import { Invoice, Vendor, DashboardStats } from "./types";

export const mockInvoices: Invoice[] = [
  {
    id: "INV-2024-001",
    vendorId: "V-CARE",
    vendorName: "CARE Analytics",
    amount: 250000,
    currency: "INR",
    invoiceDate: "2024-03-01",
    dueDate: "2024-03-31",
    status: "blocked",
    invoiceNumber: "CARE-2024-001",
    description: "Data analytics and reporting services",
    gstin: "29AABCT1234H1Z5",
    pan: "AABCT1234H",
    poNumber: "PO-2024-001",
    uploadedAt: "2024-03-05",
    processedAt: "2024-03-06",
    checks: [
      { id: "chk-1", name: "GSTIN Validation", status: "pass", message: "GSTIN verified with GST database" },
      { id: "chk-2", name: "Amount Verification", status: "fail", message: "Invoice amount exceeds contract limit" },
      { id: "chk-3", name: "Due Date Check", status: "pass", message: "Due date within acceptable range" },
      { id: "chk-4", name: "Duplicate Detection", status: "fail", message: "Similar invoice found in Q1 2024" },
    ],
    flags: [
      { id: "flag-1", type: "amount", severity: "high", message: "Invoice 15% above average for this vendor" },
      { id: "flag-2", type: "duplicate", severity: "high", message: "Potential duplicate with INV-2024-156" },
    ],
  },
  {
    id: "INV-2024-002",
    vendorId: "V-TECH",
    vendorName: "TechFlow Solutions",
    amount: 125000,
    currency: "INR",
    invoiceDate: "2024-03-02",
    dueDate: "2024-04-02",
    status: "approved",
    invoiceNumber: "TFS-2024-0542",
    description: "Cloud infrastructure and support services",
    gstin: "27AABCC1234H1Z5",
    pan: "AABCC1234H",
    poNumber: "PO-2024-002",
    uploadedAt: "2024-03-06",
    processedAt: "2024-03-06",
    checks: [
      { id: "chk-1", name: "GSTIN Validation", status: "pass", message: "GSTIN verified" },
      { id: "chk-2", name: "Amount Verification", status: "pass", message: "Amount within contract limits" },
      { id: "chk-3", name: "Due Date Check", status: "pass", message: "Due date valid" },
      { id: "chk-4", name: "Duplicate Detection", status: "pass", message: "No duplicates found" },
    ],
    flags: [],
  },
  {
    id: "INV-2024-003",
    vendorId: "V-CONS",
    vendorName: "Consulting Plus",
    amount: 175000,
    currency: "INR",
    invoiceDate: "2024-03-03",
    dueDate: "2024-03-25",
    status: "approved",
    invoiceNumber: "CP-2024-1829",
    description: "Business strategy consulting",
    gstin: "28AABCD1234H1Z5",
    pan: "AABCD1234H",
    poNumber: "PO-2024-003",
    uploadedAt: "2024-03-07",
    processedAt: "2024-03-07",
    checks: [
      { id: "chk-1", name: "GSTIN Validation", status: "pass", message: "GSTIN verified" },
      { id: "chk-2", name: "Amount Verification", status: "pass", message: "Amount verified" },
      { id: "chk-3", name: "Due Date Check", status: "pass", message: "Within terms" },
      { id: "chk-4", name: "Duplicate Detection", status: "pass", message: "Unique invoice" },
    ],
    flags: [],
  },
  {
    id: "INV-2024-004",
    vendorId: "V-SOFT",
    vendorName: "Software House",
    amount: 95000,
    currency: "INR",
    invoiceDate: "2024-03-04",
    dueDate: "2024-04-04",
    status: "approved",
    invoiceNumber: "SH-2024-2891",
    description: "Custom software development",
    gstin: "26AABCE1234H1Z5",
    pan: "AABCE1234H",
    poNumber: "PO-2024-004",
    uploadedAt: "2024-03-08",
    processedAt: "2024-03-08",
    checks: [
      { id: "chk-1", name: "GSTIN Validation", status: "pass", message: "GSTIN verified" },
      { id: "chk-2", name: "Amount Verification", status: "pass", message: "Amount verified" },
      { id: "chk-3", name: "Due Date Check", status: "pass", message: "Within terms" },
      { id: "chk-4", name: "Duplicate Detection", status: "pass", message: "Unique" },
    ],
    flags: [],
  },
];

export const mockVendors: Vendor[] = [
  {
    id: "V-CARE",
    name: "CARE Analytics",
    gstin: "29AABCT1234H1Z5",
    pan: "AABCT1234H",
    category: "Analytics",
    totalInvoices: 8,
    totalAmount: 2500000,
    riskScore: 72,
    status: "flagged",
  },
  {
    id: "V-TECH",
    name: "TechFlow Solutions",
    gstin: "27AABCC1234H1Z5",
    pan: "AABCC1234H",
    category: "IT Services",
    totalInvoices: 23,
    totalAmount: 5200000,
    riskScore: 15,
    status: "active",
  },
  {
    id: "V-CONS",
    name: "Consulting Plus",
    gstin: "28AABCD1234H1Z5",
    pan: "AABCD1234H",
    category: "Consulting",
    totalInvoices: 12,
    totalAmount: 3100000,
    riskScore: 22,
    status: "active",
  },
  {
    id: "V-SOFT",
    name: "Software House",
    gstin: "26AABCE1234H1Z5",
    pan: "AABCE1234H",
    category: "Software",
    totalInvoices: 31,
    totalAmount: 4800000,
    riskScore: 8,
    status: "active",
  },
  {
    id: "V-SUPPLY",
    name: "Supply Chain Co",
    gstin: "25AABCF1234H1Z5",
    pan: "AABCF1234H",
    category: "Logistics",
    totalInvoices: 45,
    totalAmount: 6700000,
    riskScore: 35,
    status: "active",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProcessed: 412,
  totalApproved: 389,
  totalBlocked: 12,
  approvalRate: 94.4,
  totalAmount: 12500000,
  averageProcessingTime: 2.3,
};

export const mockMonthlyData = [
  { month: "January", amount: 2100000 },
  { month: "February", amount: 2850000 },
  { month: "March", amount: 2300000 },
  { month: "April", amount: 3100000 },
  { month: "May", amount: 2800000 },
  { month: "June", amount: 3200000 },
  { month: "July", amount: 2900000 },
  { month: "August", amount: 3400000 },
  { month: "September", amount: 3100000 },
  { month: "October", amount: 2950000 },
  { month: "November", amount: 3300000 },
  { month: "December", amount: 3800000 },
];
